version: '3.8'

services:
  client:
    container_name: health_client
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./configs/conf.env
